# Generated by Django 2.1.5 on 2019-01-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
