# Generated by Django 2.1.5 on 2019-01-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Employer'), (2, 'Employee')], null=True),
        ),
    ]
