# Generated by Django 2.1.5 on 2019-01-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_survey_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='country',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Kyrgyzstan'), (2, 'Tajikistan')], default=1),
            preserve_default=False,
        ),
    ]
