# Generated by Django 2.1.5 on 2019-01-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_survey_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='country',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Kyrgyzstan'), (1, 'Tajikistan'), (2, 'Kazakhstan')]),
        ),
    ]
