# Generated by Django 2.1.5 on 2019-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190127_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='scale1',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
