# Generated by Django 2.1.5 on 2019-01-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190128_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='scale2',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='scale3',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='scale4',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='scale5',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='scale6',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='scale7',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='scale8',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
