# Generated by Django 2.1.5 on 2019-01-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190128_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='extra4',
            field=models.PositiveSmallIntegerField(choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='extra5',
            field=models.PositiveSmallIntegerField(choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='extra6',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
