# Generated by Django 2.1.5 on 2019-01-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190128_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='campus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Naryn'), (1, 'Khorog'), (2, 'Tekeli')], default=0),
            preserve_default=False,
        ),
    ]
