# Generated by Django 2.1.5 on 2019-01-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_survey_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='email_roommate',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='survey',
            name='want_roommate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='country',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Kyrgyzstan'), (1, 'Tajikistan'), (2, 'Kazakhstan'), (3, 'Pakistan')]),
        ),
    ]
